services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@pers123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  sqlserver_data:
  keycloak_data:
