name: Backend CI for CEventService

on:
  push:
    branches: [main, develop, "feature/*", "fix/*"]
  pull_request:
    branches: [main, develop, "feature/*", "fix/*"]
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for CEventService.API
        working-directory: ./apps/CEventService.API
        run: dotnet restore

      - name: Build CEventService.API
        working-directory: ./apps/CEventService.API
        run: dotnet build --no-restore --configuration Release

      - name: Restore dependencies for CEventService.Tests
        working-directory: ./apps/CEventService.Tests
        run: dotnet restore

      - name: Build CEventService.Tests
        working-directory: ./apps/CEventService.Tests
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        working-directory: ./apps/CEventService.Tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Upload test coverage results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: apps/CEventService.Tests/TestResults
